### PR TITLE
Add plural_name key for item objects, allows for better formatting.

### PR DESCRIPTION
**Pull request by xPolar**

### CODE REVIEW

**Review by KAJdev — COMMENTED** [review]
Having 'plural' be the actual string of a plural name might give us more control?

**Comment by xPolar** [comment]
True, thought about doing `plural` but you said `plural_name` in the other PR so I went with `plural_name`.

**Comment by KAJdev** [comment]
No meant having strings that are the plural version of the names, not a bool value.

**Comment by xPolar** [comment]
Ah, yeah would make sense.

**Review by KAJdev — APPROVED** [review]

**Pull request merged**
