### PR TITLE
Change 'Bagguete' to 'Bagguetes' if amount purchased is greater than …

### PR DESCRIPTION
**Pull request by xPolar**
Code doesn't need testing as it's a pretty simple inline if statement. This PR isn't needed but it's for my OCD.

### CODE REVIEW

**Review by KAJdev — APPROVED** [review]

**Comment by DirtFrosting** [comment]
Do the same for all countable types of bread. Same code as above can be used. (bagels for an example).

**Comment by KAJdev** [comment]
> Do the same for all countable types of bread. Same code as above can be used. (bagels for an example).

This is for every bread type. Not just baguettes.

**Comment by DirtFrosting** [comment]
Wheat breads sounds incredibly wrong.

**Comment by xPolar** [comment]
Possibly the option to have a `plural` field in each bread type, would be a simple fix to check if the bread type can be plural.

**Comment by KAJdev** [comment]
> Possibly the option to have a `plural` field in each bread type, would be a simple fix to check if the bread type can be plural.

yeah, a 'plural_name' would be a good idea to put as a field.

**Comment by xPolar** [comment]
Just realized can do `name.split(" ")[-1].lower().endswith("bread")` to check if it sounds good, wouldn't need to add plural field. Muffins sounds normal, bagels do as well, but anything ending with bread doesn't.

**Comment by KAJdev** [comment]
it wouldn't be future proof. Might be more maintainable with the plural field, to be honest.

**Comment by xPolar** [comment]
True, can make a PR for it right now.

**Comment by KAJdev** [comment]
Sounds good.

**Pull request merged**
